# Generated by Django 5.0.2 on 2024-02-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('video_card', 'Видео-карта'), ('cpu', 'Процессор'), ('cooler', 'Охлаждение'), ('ram', 'Оперативная память'), ('system_board', 'Материнская плата'), ('hhd', 'Жёсткий диск'), ('ssd', 'Диск SSD'), ('optical_drive', 'Оптический привод'), ('psu', 'Блок питания'), ('body', 'Корпус'), ('os', 'Система')], max_length=100)),
            ],
        ),
    ]
