# Generated by Django 5.0.2 on 2024-02-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.TextField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('category', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='products_picture/')),
                ('powerScale', models.IntegerField(default=0)),
                ('importance', models.IntegerField(default=0)),
                ('sale', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
