# Generated by Django 5.0.2 on 2024-02-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descripton', models.TextField()),
                ('price', models.TextField()),
                ('brand', models.TextField()),
                ('model', models.TextField()),
                ('year', models.IntegerField(default=0)),
                ('category', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers_picture/', verbose_name='Изображение')),
                ('powerScale', models.IntegerField(default=0)),
                ('importance', models.IntegerField(default=0)),
                ('is_game', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('sale', models.IntegerField(default=0)),
                ('powerUnit', models.TextField()),
                ('wifi', models.TextField()),
                ('operatingSystem', models.TextField()),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body', to='computers.product')),
                ('cooler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooler', to='computers.product')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='computers.product')),
                ('disk1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disk1', to='computers.product')),
                ('disk2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='disk2', to='computers.product')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dvd', to='computers.product')),
                ('hdd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hdd', to='computers.product')),
                ('headset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='headset', to='computers.product')),
                ('keyboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='keyboard', to='computers.product')),
                ('monitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monitor', to='computers.product')),
                ('motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='motherboard', to='computers.product')),
                ('mouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouse', to='computers.product')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ram', to='computers.product')),
                ('soundCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='soundCard', to='computers.product')),
                ('videoCard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='videoCard', to='computers.product')),
            ],
        ),
    ]
