# Generated by Django 5.0.2 on 2024-02-15 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('powerful', 'Мощный компьютер'), ('gaming', 'Игровой компьютер'), ('cheap', 'Недорогой компьютер')], max_length=100, verbose_name='Раздел')),
                ('name', models.CharField(max_length=255, verbose_name='Название компьютера')),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers_picture/', verbose_name='Изображение')),
                ('descripton', models.TextField(verbose_name='Описание компьютера')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('audio_card', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_card', to='computers.audiocard', verbose_name='Система')),
                ('body', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body', to='computers.body', verbose_name='Корпус')),
                ('cooler', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooler', to='computers.cooler', verbose_name='Охлаждение')),
                ('cpu', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='computers.cpu', verbose_name='Процессор')),
                ('hhd', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hhd', to='computers.hard', verbose_name='Жёсткий диск')),
                ('optical_drive', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optical_drive', to='computers.dvddrive', verbose_name='Оптический привод')),
                ('os', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='os', to='computers.osystem', verbose_name='Система')),
                ('psu', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psu', to='computers.powerunit', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ram', to='computers.ram', verbose_name='Оперативная память')),
                ('ssd_1', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_1', to='computers.ssd', verbose_name='Диск SSD 1')),
                ('ssd_2', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_2', to='computers.ssd', verbose_name='Диск SSD 2')),
                ('system_board', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_board', to='computers.motherboard', verbose_name='Материнская плата')),
                ('video_card', models.ForeignKey(limit_choices_to={'category': ()}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.videocard', verbose_name='Видео-карта')),
                ('wifi', models.ForeignKey(blank=True, limit_choices_to={'category': ()}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wifi', to='computers.wifiadapter', verbose_name='Система')),
            ],
        ),
    ]
