# Generated by Django 5.0.2 on 2024-02-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descripton', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('body', models.ForeignKey(limit_choices_to={'category': 'body'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body', to='computers.accessoriestype', verbose_name='Корпус')),
                ('cooler', models.ForeignKey(limit_choices_to={'category': 'cooler'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooler', to='computers.accessoriestype', verbose_name='Охлаждение')),
                ('cpu', models.ForeignKey(limit_choices_to={'category': 'cpu'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='computers.accessoriestype', verbose_name='Процессор')),
                ('hhd', models.ForeignKey(limit_choices_to={'category': 'hhd'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hhd', to='computers.accessoriestype', verbose_name='Жёсткий диск')),
                ('optical_drive', models.ForeignKey(limit_choices_to={'category': 'optical_drive'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optical_drive', to='computers.accessoriestype', verbose_name='Оптический привод')),
                ('os', models.ForeignKey(limit_choices_to={'category': 'os'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='os', to='computers.accessoriestype', verbose_name='Система')),
                ('psu', models.ForeignKey(limit_choices_to={'category': 'psu'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psu', to='computers.accessoriestype', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(limit_choices_to={'category': 'ram'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ram', to='computers.accessoriestype', verbose_name='Оперативная память')),
                ('ssd', models.ForeignKey(limit_choices_to={'category': 'ssd'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd', to='computers.accessoriestype', verbose_name='Диск SSD')),
                ('system_board', models.ForeignKey(limit_choices_to={'category': 'system_board'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_board', to='computers.accessoriestype', verbose_name='Материнская плата')),
                ('video_card', models.ForeignKey(limit_choices_to={'category': 'video_card'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.accessoriestype', verbose_name='Видео-карта')),
            ],
        ),
    ]
