# Generated by Django 5.0.2 on 2024-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoriestype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories_picture/'),
        ),
        migrations.AddField(
            model_name='accessoriestype',
            name='is_cheap',
            field=models.BooleanField(default=False, verbose_name='Недорогой компьютер'),
        ),
        migrations.AddField(
            model_name='accessoriestype',
            name='is_gaming',
            field=models.BooleanField(default=False, verbose_name='Игровой компьютер'),
        ),
        migrations.AddField(
            model_name='accessoriestype',
            name='is_powerful',
            field=models.BooleanField(default=False, verbose_name='Мощный компьютер'),
        ),
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='computers_picture/'),
        ),
    ]
