# Generated by Django 5.0.2 on 2024-02-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='audio_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_card', to='computers.audiocard', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body', to='computers.body', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooler', to='computers.cooler', verbose_name='Охлаждение'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='computers.cpu', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hhd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hhd', to='computers.hard', verbose_name='Жёсткий диск'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='optical_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optical_drive', to='computers.dvddrive', verbose_name='Оптический привод'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='os', to='computers.osystem', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='psu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psu', to='computers.powerunit', verbose_name='Блок питания'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ram', to='computers.ram', verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_1', to='computers.ssd', verbose_name='Диск SSD 1'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_2', to='computers.ssd', verbose_name='Диск SSD 2'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='system_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_board', to='computers.motherboard', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.videocard', verbose_name='Видео-карта'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='wifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wifi', to='computers.wifiadapter', verbose_name='Система'),
        ),
    ]
