# Generated by Django 5.0.2 on 2024-02-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0003_alter_computer_audio_card_alter_computer_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headset',
            options={'verbose_name': 'Гарнитура', 'verbose_name_plural': 'Гарнитуры'},
        ),
        migrations.AlterField(
            model_name='computer',
            name='audio_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audio_card', to='computers.audiocard', verbose_name='Звуковая карта'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='os', to='computers.osystem', verbose_name='Операционная система'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='wifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wifi', to='computers.wifiadapter', verbose_name='Wi-Fi Адаптер'),
        ),
    ]
