# Generated by Django 5.0.2 on 2024-02-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0004_remove_accessoriestype_is_cheap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoriestype',
            name='category',
            field=models.CharField(choices=[('video_card', 'Видео-карта'), ('cpu', 'Процессор'), ('cooler', 'Охлаждение'), ('ram', 'Оперативная память'), ('system_board', 'Материнская плата'), ('hhd', 'Жёсткий диск'), ('ssd', 'Диск SSD'), ('optical_drive', 'Оптический привод'), ('psu', 'Блок питания'), ('body', 'Корпус'), ('os', 'Система')], max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='accessoriestype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories_picture/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='accessoriestype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название комплектующей'),
        ),
        migrations.AlterField(
            model_name='accessoriestype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='descripton',
            field=models.TextField(verbose_name='Описание компьютера'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='computers_picture/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компьютера'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
