# Generated by Django 5.0.2 on 2024-02-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0005_alter_accessoriestype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='is_cheap',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='is_gaming',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='is_powerful',
        ),
    ]
