# Generated by Django 5.0.2 on 2024-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0006_remove_computer_is_cheap_remove_computer_is_gaming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='section',
            field=models.CharField(choices=[('powerful', 'Мощный компьютер'), ('gaming', 'Игровой компьютер'), ('cheap', 'Недорогой компьютер')], default=1, max_length=100, verbose_name='Раздел'),
            preserve_default=False,
        ),
    ]
