# Generated by Django 5.0.2 on 2024-02-13 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0007_computer_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoriesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название комплектующей')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accessories_picture/', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(choices=[('video_card', 'Видео-карта'), ('cpu', 'Процессор'), ('cooler', 'Охлаждение'), ('ram', 'Оперативная память'), ('system_board', 'Материнская плата'), ('hhd', 'Жёсткий диск'), ('ssd', 'Диск SSD'), ('optical_drive', 'Оптический привод'), ('psu', 'Блок питания'), ('body', 'Корпус'), ('os', 'Система'), ('wifi', 'WI-FI адаптер'), ('audio_card', 'Звуковая карта'), ('mouse', 'Мышь'), ('keyboard', 'Клавиатура'), ('display', 'Монитор'), ('headset', 'Гарнитура')], max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ssd',
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'ssd'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_1', to='computers.accessoriescategory', verbose_name='Диск SSD 1'),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'ssd'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ssd_2', to='computers.accessoriescategory', verbose_name='Диск SSD 2'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='body',
            field=models.ForeignKey(limit_choices_to={'category': 'body'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='body', to='computers.accessoriescategory', verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cooler',
            field=models.ForeignKey(limit_choices_to={'category': 'cooler'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cooler', to='computers.accessoriescategory', verbose_name='Охлаждение'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='cpu',
            field=models.ForeignKey(limit_choices_to={'category': 'cpu'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='computers.accessoriescategory', verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='hhd',
            field=models.ForeignKey(limit_choices_to={'category': 'hhd'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hhd', to='computers.accessoriescategory', verbose_name='Жёсткий диск'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='optical_drive',
            field=models.ForeignKey(limit_choices_to={'category': 'optical_drive'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='optical_drive', to='computers.accessoriescategory', verbose_name='Оптический привод'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(limit_choices_to={'category': 'os'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='os', to='computers.accessoriescategory', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='psu',
            field=models.ForeignKey(limit_choices_to={'category': 'psu'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psu', to='computers.accessoriescategory', verbose_name='Блок питания'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.ForeignKey(limit_choices_to={'category': 'ram'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ram', to='computers.accessoriescategory', verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='system_board',
            field=models.ForeignKey(limit_choices_to={'category': 'system_board'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_board', to='computers.accessoriescategory', verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.ForeignKey(limit_choices_to={'category': 'video_card'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.accessoriescategory', verbose_name='Видео-карта'),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accesories_img/', verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название модели')),
                ('socket', models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокет')),
                ('cache', models.BigIntegerField(blank=True, null=True, verbose_name='Кэш')),
                ('cores', models.IntegerField(blank=True, null=True, verbose_name='Количество ядер')),
                ('processor_frequency', models.IntegerField(blank=True, null=True, verbose_name='Частота ядер')),
                ('tech_process', models.IntegerField(blank=True, null=True, verbose_name='Техпроцесс')),
                ('core', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ядро')),
                ('max_frequency', models.BigIntegerField(blank=True, null=True, verbose_name='Максимальная частота с Turbo Boost')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='computers.accessoriescategory', verbose_name='Марка товара')),
            ],
        ),
        migrations.DeleteModel(
            name='AccessoriesType',
        ),
    ]
