# Generated by Django 5.0.2 on 2024-02-13 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0009_remove_accessoriescategory_price_accessory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='processor_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Частота процессора'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.ForeignKey(limit_choices_to={'category': 'video_card'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.accessory', verbose_name='Видео-карта'),
        ),
    ]
