# Generated by Django 5.0.2 on 2024-02-13 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0010_alter_accessory_processor_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.ForeignKey(limit_choices_to={'category': 'video_card'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='video_card', to='computers.accessoriescategory', verbose_name='Видео-карта'),
        ),
        migrations.RemoveField(
            model_name='accessoriescategory',
            name='name',
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='cache',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Кэш'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='core',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ядро'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество ядер'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='max_frequency',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Максимальная частота с Turbo Boost'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название модели'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='processor_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Частота процессора'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='socket',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сокет'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='tech_process',
            field=models.IntegerField(blank=True, null=True, verbose_name='Техпроцесс'),
        ),
        migrations.AlterField(
            model_name='accessoriescategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accesories_img/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='accessoriescategory',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='computers.brand', verbose_name='Название бренда'),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
