# Generated by Django 5.0.2 on 2024-02-16 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('computers', '0002_computer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('stars', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='feedBacks_picture/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='computers.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('houseOrComplex', models.TextField()),
                ('homeNumber', models.IntegerField(default=0)),
                ('email', models.TextField()),
                ('phoneNumber', models.TextField()),
                ('fullName', models.TextField()),
                ('willBeDeliveredAt', models.DateTimeField()),
                ('importance', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='computers.product')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
            ],
        ),
    ]
